# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0133_fatturacliente_banca_di_appoggio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BollaFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('codice', models.CharField(max_length=9)),
                ('data', models.DateField()),
                ('oggetto', models.CharField(null=True, blank=True, max_length=150)),
                ('fatturata', models.BooleanField(default=False)),
                ('peso_netto', models.CharField(null=True, blank=True, max_length=50)),
                ('peso_lordo', models.CharField(null=True, blank=True, max_length=50)),
                ('numero_colli', models.PositiveIntegerField(null=True, blank=True)),
                ('note', models.TextField(null=True, blank=True)),
                ('cancellato', models.BooleanField(default=False)),
                ('aspetto_esteriore', models.ForeignKey(null=True, to='anagrafiche.TipoAspettoEsteriore', blank=True)),
                ('causale_trasporto', models.ForeignKey(null=True, to='anagrafiche.TipoCausaleTrasporto', blank=True)),
                ('commessa', models.ForeignKey(to='anagrafiche.Commessa', related_name='bolle_fornitori')),
                ('destinazione', models.ForeignKey(null=True, to='anagrafiche.Indirizzo', blank=True)),
                ('fornitore', models.ForeignKey(to='anagrafiche.Entita')),
                ('porto', models.ForeignKey(null=True, to='anagrafiche.TipoPorto', blank=True)),
                ('trasporto_a_cura', models.ForeignKey(null=True, to='anagrafiche.TipoTrasportoACura', blank=True)),
                ('vettore', models.ForeignKey(null=True, related_name='bolle_trasportate_fornitori', to='anagrafiche.Entita', blank=True)),
            ],
            options={
                'verbose_name_plural': 'bolle fornitori',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FatturaFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('codice', models.CharField(max_length=9)),
                ('data', models.DateField()),
                ('oggetto', models.CharField(null=True, blank=True, max_length=150)),
                ('imponibile', models.DecimalField(decimal_places=2, max_digits=15, default=0)),
                ('sconto_euro', models.DecimalField(decimal_places=2, max_digits=12, default=0)),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, max_digits=6, default=0)),
                ('imponibile_netto', models.DecimalField(decimal_places=2, max_digits=15, default=0)),
                ('totale_iva', models.DecimalField(decimal_places=2, max_digits=15, default=0)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=15, default=0)),
                ('note', models.TextField(null=True, blank=True)),
                ('cancellato', models.BooleanField(default=False)),
                ('aliquota_IVA', models.ForeignKey(null=True, to='anagrafiche.AliquotaIVA', blank=True)),
                ('banca_di_appoggio', models.ForeignKey(null=True, to='anagrafiche.ContoCorrente', blank=True)),
                ('commessa', models.ForeignKey(to='anagrafiche.Commessa', related_name='fatture_fornitori')),
                ('destinazione', models.ForeignKey(null=True, to='anagrafiche.Indirizzo', blank=True)),
                ('fornitore', models.ForeignKey(to='anagrafiche.Entita')),
                ('pagamento', models.ForeignKey(to='anagrafiche.TipoPagamento', default=1)),
            ],
            options={
                'verbose_name_plural': 'fatture fornitori',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrdineFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('codice', models.CharField(max_length=9)),
                ('data', models.DateField()),
                ('oggetto', models.CharField(null=True, blank=True, max_length=150)),
                ('bollettato', models.BooleanField(default=False)),
                ('fatturato', models.BooleanField(default=False)),
                ('persona_di_riferimento', models.CharField(blank=True, max_length=100, default='')),
                ('disegni_costruttivi', models.BooleanField(default=True)),
                ('relazione_di_calcolo', models.BooleanField(default=True)),
                ('tipo_di_acciaio', models.CharField(blank=True, max_length=150, default='')),
                ('spessori', models.CharField(blank=True, max_length=150, default='')),
                ('zincatura', models.CharField(blank=True, max_length=150, default='')),
                ('classe_di_esecuzione', models.CharField(blank=True, max_length=150, default='')),
                ('wps', models.CharField(blank=True, max_length=150, default='')),
                ('verniciatura', models.CharField(blank=True, max_length=150, default='')),
                ('sconto_euro', models.DecimalField(decimal_places=2, max_digits=12, default=0)),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, max_digits=6, default=0)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=15, default=0)),
                ('totale_su_stampa', models.BooleanField(default=True)),
                ('note', models.TextField(null=True, blank=True)),
                ('cancellato', models.BooleanField(default=False)),
                ('aliquota_IVA', models.ForeignKey(null=True, to='anagrafiche.AliquotaIVA', blank=True)),
                ('commessa', models.ForeignKey(to='anagrafiche.Commessa', related_name='ordini_fornitori')),
                ('destinazione', models.ForeignKey(null=True, to='anagrafiche.Indirizzo', blank=True)),
                ('fornitore', models.ForeignKey(to='anagrafiche.Entita')),
                ('pagamento', models.ForeignKey(to='anagrafiche.TipoPagamento', default=1)),
            ],
            options={
                'verbose_name_plural': 'ordini fornitori',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PreventivoFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('codice', models.CharField(max_length=9)),
                ('codice_preventivo_fornitore', models.CharField(null=True, blank=True, max_length=15)),
                ('data', models.DateField()),
                ('data_preventivo_fornitore', models.DateField()),
                ('oggetto', models.CharField(null=True, blank=True, max_length=150)),
                ('accettato', models.BooleanField(default=False)),
                ('persona_di_riferimento', models.CharField(blank=True, max_length=150, default='')),
                ('disegni_costruttivi', models.BooleanField(default=True)),
                ('relazione_di_calcolo', models.BooleanField(default=True)),
                ('tipo_di_acciaio', models.CharField(blank=True, max_length=150, default='')),
                ('spessori', models.CharField(blank=True, max_length=150, default='')),
                ('zincatura', models.CharField(blank=True, max_length=150, default='')),
                ('classe_di_esecuzione', models.CharField(blank=True, max_length=150, default='')),
                ('wps', models.CharField(blank=True, max_length=150, default='')),
                ('verniciatura', models.CharField(blank=True, max_length=150, default='')),
                ('totale', models.DecimalField(decimal_places=2, max_digits=15, default=0)),
                ('note', models.TextField(null=True, blank=True)),
                ('cancellato', models.BooleanField(default=False)),
                ('aliquota_IVA', models.ForeignKey(null=True, to='anagrafiche.AliquotaIVA', blank=True)),
                ('commessa', models.ForeignKey(null=True, related_name='preventivi_fornitori', to='anagrafiche.Commessa', blank=True)),
                ('destinazione', models.ForeignKey(null=True, to='anagrafiche.Indirizzo', blank=True)),
                ('fornitore', models.ForeignKey(to='anagrafiche.Entita')),
                ('pagamento', models.ForeignKey(to='anagrafiche.TipoPagamento', default=1)),
            ],
            options={
                'verbose_name_plural': 'preventivi fornitori',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RigaBollaFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('fatturata', models.BooleanField(default=False)),
                ('articolo_descrizione', models.CharField(max_length=1000)),
                ('articolo_unita_di_misura', models.CharField(choices=[('PZ', 'pz'), ('NR', 'n.'), ('SC', 'sc'), ('ME', 'm'), ('M2', 'm²'), ('CM', 'cm'), ('MM', 'mm'), ('KG', 'kg'), ('HG', 'hg'), ('LI', 'l'), ('ML', 'ml')], max_length=2, default='NR')),
                ('quantita', models.DecimalField(decimal_places=2, verbose_name='quantità', max_digits=15)),
                ('note', models.CharField(blank=True, max_length=500, default='')),
                ('cancellato', models.BooleanField(default=False)),
                ('articolo', models.ForeignKey(to='anagrafiche.Articolo')),
                ('bolla', models.ForeignKey(to='anagrafiche.BollaFornitore', related_name='righe')),
            ],
            options={
                'verbose_name_plural': 'righe bolle fornitori',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RigaFatturaFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('articolo_descrizione', models.CharField(max_length=1000)),
                ('articolo_prezzo', models.DecimalField(decimal_places=2, max_digits=13)),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, max_digits=5, default=0)),
                ('articolo_unita_di_misura', models.CharField(choices=[('PZ', 'pz'), ('NR', 'n.'), ('SC', 'sc'), ('ME', 'm'), ('M2', 'm²'), ('CM', 'cm'), ('MM', 'mm'), ('KG', 'kg'), ('HG', 'hg'), ('LI', 'l'), ('ML', 'ml')], max_length=2, default='NR')),
                ('quantita', models.DecimalField(decimal_places=2, verbose_name='quantità', max_digits=15)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.CharField(blank=True, max_length=500, default='')),
                ('cancellato', models.BooleanField(default=False)),
                ('articolo', models.ForeignKey(to='anagrafiche.Articolo')),
                ('fattura', models.ForeignKey(to='anagrafiche.FatturaFornitore', related_name='righe')),
                ('riga_bolla', models.OneToOneField(null=True, related_name='riga_fattura', to='anagrafiche.RigaBollaFornitore', blank=True)),
            ],
            options={
                'verbose_name_plural': 'righe fatture fornitori',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RigaOrdineFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('articolo_descrizione', models.CharField(max_length=1000)),
                ('articolo_prezzo', models.DecimalField(decimal_places=2, max_digits=13)),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, max_digits=5, default=0)),
                ('articolo_unita_di_misura', models.CharField(choices=[('PZ', 'pz'), ('NR', 'n.'), ('SC', 'sc'), ('ME', 'm'), ('M2', 'm²'), ('CM', 'cm'), ('MM', 'mm'), ('KG', 'kg'), ('HG', 'hg'), ('LI', 'l'), ('ML', 'ml')], max_length=2, default='NR')),
                ('bollettata', models.BooleanField(default=False)),
                ('fatturata', models.BooleanField(default=False)),
                ('quantita', models.DecimalField(decimal_places=2, verbose_name='quantità', max_digits=15)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.CharField(blank=True, max_length=500, default='')),
                ('cancellato', models.BooleanField(default=False)),
                ('articolo', models.ForeignKey(to='anagrafiche.Articolo')),
                ('ordine', models.ForeignKey(to='anagrafiche.OrdineFornitore', related_name='righe')),
            ],
            options={
                'verbose_name_plural': 'righe ordini fornitori',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RigaPreventivoFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('articolo_descrizione', models.CharField(max_length=1000)),
                ('articolo_codice_fornitore', models.CharField(null=True, blank=True, max_length=200)),
                ('articolo_prezzo', models.DecimalField(decimal_places=2, max_digits=13)),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, max_digits=5, default=0)),
                ('articolo_unita_di_misura', models.CharField(choices=[('PZ', 'pz'), ('NR', 'n.'), ('SC', 'sc'), ('ME', 'm'), ('M2', 'm²'), ('CM', 'cm'), ('MM', 'mm'), ('KG', 'kg'), ('HG', 'hg'), ('LI', 'l'), ('ML', 'ml')], max_length=2, default='NR')),
                ('accettata', models.BooleanField(default=False)),
                ('data_consegna', models.DateField(null=True)),
                ('quantita', models.DecimalField(decimal_places=2, verbose_name='quantità', max_digits=15)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.CharField(blank=True, max_length=500, default='')),
                ('cancellato', models.BooleanField(default=False)),
                ('articolo', models.ForeignKey(to='anagrafiche.Articolo')),
                ('preventivo', models.ForeignKey(to='anagrafiche.PreventivoFornitore', related_name='righe')),
            ],
            options={
                'verbose_name_plural': 'righe preventivi fornitori',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='rigaordinefornitore',
            name='riga_preventivo',
            field=models.OneToOneField(null=True, related_name='riga_ordine', to='anagrafiche.RigaPreventivoFornitore', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='rigafatturafornitore',
            name='riga_ordine',
            field=models.OneToOneField(null=True, related_name='riga_fattura', to='anagrafiche.RigaOrdineFornitore', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='rigabollafornitore',
            name='riga_ordine',
            field=models.OneToOneField(null=True, related_name='riga_bolla', to='anagrafiche.RigaOrdineFornitore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterModelOptions(
            name='rigapreventivocliente',
            options={'verbose_name_plural': 'righe preventivi clienti'},
        ),
    ]
